# Generated by Django 4.1.7 on 2023-03-27 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="datetime",
            new_name="visit_date",
        ),
        migrations.AddField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="upload",
            field=models.ImageField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLrWVtomuKNMXY38fiZ6HM7PJSiE7ubfdfvQbdAXC9&s",
                upload_to="uploads/%Y/%m/%d/",
            ),
        ),
    ]
