# Generated by Django 4.1.7 on 2023-03-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_organisations"),
        ("posts", "0002_rename_datetime_post_visit_date_post_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userprofile",
            ),
        ),
    ]
