# Generated by Django 4.1.7 on 2023-03-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_recipients_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
