# Generated by Django 4.1.7 on 2023-03-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
        ("posts", "0007_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="orgs.org",
            ),
        ),
    ]
