# Generated by Django 4.1.7 on 2023-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_post_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="upload",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
