# Generated by Django 4.1.7 on 2023-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_post_visit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="visit_date",
            field=models.DateTimeField(),
        ),
    ]
