# Generated by Django 4.1.7 on 2023-03-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="upload",
            field=models.ImageField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLrWVtomuKNMXY38fiZ6HM7PJSiE7ubfdfvQbdAXC9&s",
                upload_to="uploads/",
            ),
        ),
    ]
