# Generated by Django 4.1.7 on 2023-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0002_alter_org_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="stars",
            field=models.IntegerField(default=0),
        ),
    ]
