# Generated by Django 4.1.7 on 2023-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organisations",
            field=models.ManyToManyField(related_name="organisations", to="orgs.org"),
        ),
    ]
