# Generated by Django 4.1.7 on 2023-03-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_post_author"),
        ("accounts", "0002_userprofile_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pic",
            field=models.ImageField(
                default="https://i.pinimg.com/originals/3d/66/78/3d667893c5788613ff3590ca218a9cb2.jpg",
                upload_to="uploads/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.post",
            ),
        ),
    ]
