# Generated by Django 4.1.7 on 2023-03-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_pic_userprofile_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="pic",
        ),
    ]
