# Generated by Django 4.1.7 on 2023-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pic",
            field=models.ImageField(
                default="https://i.pinimg.com/originals/3d/66/78/3d667893c5788613ff3590ca218a9cb2.jpg",
                upload_to="uploads/",
            ),
        ),
    ]
