# Generated by Django 4.1.7 on 2023-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userprofile_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="stars",
            field=models.IntegerField(),
        ),
    ]
